export const USER_FEATURE_SCHEMA = {
  identity: [
    'id',
    'name',
    'city',
    'ageGroup',
    'segment',
    'preferredChannel',
  ],
  vehicle: [
    'vehicleType',
    'vehicleAgeYears',
  ],
  serviceState: [
    'etcUsage',
    'walletUsage',
    'parkingUsage',
    'chargingUsage',
    'roadsideEnabled',
    'insuranceStatus',
  ],
  engagement: [
    'engagementScore',
    'lastActiveDays',
    'loyaltyPoints',
    'interests',
  ],
  activitySignals: [
    'activityCount',
    'walletTopups',
    'referralShares',
    'logins',
    'etcTrips',
    'parkingPayments',
    'carWashBookings',
    'evCharges',
    'insuranceViews',
    'roadsideViews',
    'rewardRedemptions',
    'lastActivityDate',
    'totalPoints',
  ],
};

export const MISSION_TEMPLATE_SCHEMA = {
  templateId: 'stable mission template key',
  scenario: 'user scenario this template addresses',
  objective: 'target business or behavior outcome',
  category: 'Hằng ngày | Chiến dịch | Dịch vụ | An toàn | EV | Giới thiệu',
  eligibility: 'hard rules that decide whether mission can be shown',
  scoringSignals: 'soft ranking signals used to personalize priority',
  progressLogic: 'how progress is counted from product events',
  nextActionLogic: 'the recommended immediate action shown in UI',
  rewardPolicy: 'xp + loyalty reward structure',
  explanationPolicy: 'how AI explains the recommendation',
};

export const MISSION_TEMPLATE_LIBRARY = [
  {
    templateId: 'M-ONBOARDING-7D',
    scenario: 'New User Onboarding',
    objective: 'first-value actions and early habit formation',
    category: 'Hằng ngày',
    eligibility: ['segment is New User or Light User'],
    scoringSignals: [
      'new user segment',
      'low wallet usage',
      'few logins',
      'few or no activated services',
    ],
    progressLogic: [
      'complete profile',
      'link vehicle',
      'top up wallet once',
      'open or activate first service',
    ],
    nextActionLogic: 'show the smallest unfinished step first',
    rewardPolicy: 'moderate XP, early Loyalty reward, visible first badge progress',
    explanationPolicy: 'frame as simple first-week onboarding path',
  },
  {
    templateId: 'M-COME-BACK',
    scenario: 'Retention / Inactive User',
    objective: 'fast reactivation with low friction',
    category: 'Hằng ngày',
    eligibility: ['lastActiveDays >= 20 or inactive segment'],
    scoringSignals: [
      'high lastActiveDays',
      'low engagement score',
      'low recent logins',
      'remaining loyalty balance',
    ],
    progressLogic: [
      'app open',
      'view one personalized reward or service',
      'complete one easy action',
    ],
    nextActionLogic: 'surface a one-minute comeback mission',
    rewardPolicy: 'small but immediate reward',
    explanationPolicy: 'justify with churn risk and quick-win design',
  },
  {
    templateId: 'M-DAILY-LOOP',
    scenario: 'Daily Engagement',
    objective: 'weekly return behavior',
    category: 'Hằng ngày',
    eligibility: ['ETC or wallet or parking can be used repeatedly'],
    scoringSignals: [
      'high ETC frequency',
      'wallet usage gap',
      'parking usage gap',
      'recent transaction count',
    ],
    progressLogic: [
      'ETC trip',
      'wallet top-up',
      'parking payment',
    ],
    nextActionLogic: 'promote the easiest repeat transaction left this week',
    rewardPolicy: 'habit-loop XP and medium Loyalty reward',
    explanationPolicy: 'explain repeat engagement rationale',
  },
  {
    templateId: 'M-SERVICE-DISCOVERY',
    scenario: 'Service Discovery / Cross Service',
    objective: 'activate additional VETC services',
    category: 'Dịch vụ',
    eligibility: ['at least one service gap exists'],
    scoringSignals: [
      'no or low parking usage',
      'no roadside activation',
      'insurance viewed but not used',
      'explorer segment',
    ],
    progressLogic: [
      'open a new service',
      'activate a new service',
      'complete first transaction in that service',
    ],
    nextActionLogic: 'recommend the nearest high-fit unused service',
    rewardPolicy: 'higher XP and cross-service Loyalty reward',
    explanationPolicy: 'name the service gap directly',
  },
  {
    templateId: 'M-SAFETY-CHECK',
    scenario: 'Responsible Mobility',
    objective: 'increase protection coverage and maintenance behavior',
    category: 'An toàn',
    eligibility: ['insurance gap or roadside gap or older vehicle'],
    scoringSignals: [
      'insurance expiring or missing',
      'roadside disabled',
      'vehicleAgeYears >= 8',
      'safety-focused segment',
    ],
    progressLogic: [
      'view insurance',
      'view roadside',
      'activate coverage or reminder',
    ],
    nextActionLogic: 'push the highest-urgency safety action first',
    rewardPolicy: 'meaningful reward tied to responsible behavior',
    explanationPolicy: 'explain urgency and protection benefit',
  },
  {
    templateId: 'M-EV-WEEK',
    scenario: 'EV Owner',
    objective: 'grow EV ecosystem usage',
    category: 'EV',
    eligibility: ['vehicleType is EV or EV segment'],
    scoringSignals: [
      'charging usage',
      'EV interest',
      'active EV campaign',
      'charger exploration gap',
    ],
    progressLogic: [
      'charge at partner station',
      'use a new station',
      'redeem EV reward',
    ],
    nextActionLogic: 'promote the nearest or newest charger opportunity',
    rewardPolicy: 'higher EV-specific reward',
    explanationPolicy: 'explain EV fit and campaign relevance',
  },
  {
    templateId: 'M-REFERRAL',
    scenario: 'Referral Growth',
    objective: 'acquire new users through existing engaged users',
    category: 'Giới thiệu',
    eligibility: ['engagement high or referral candidate or prior share'],
    scoringSignals: [
      'engagement score',
      'loyalty points',
      'referral share history',
      'high-loyalty segment',
    ],
    progressLogic: [
      'share referral code',
      'friend links vehicle',
      'friend completes first qualifying action',
    ],
    nextActionLogic: 'push share or conversion follow-up based on current progress',
    rewardPolicy: 'high payout because acquisition is valuable',
    explanationPolicy: 'explain growth fit and social behavior evidence',
  },
  {
    templateId: 'M-PROGRESSION',
    scenario: 'Long-Term Progression',
    objective: 'sustain high-value engaged users',
    category: 'Chiến dịch',
    eligibility: ['high loyalty or high engagement'],
    scoringSignals: [
      'loyalty balance',
      'engagement score',
      'multi-service behavior',
      'badge scarcity potential',
    ],
    progressLogic: [
      'complete multiple action types in one period',
      'cross-service milestone',
      'rare badge unlock threshold',
    ],
    nextActionLogic: 'show the missing action type required for completion',
    rewardPolicy: 'high XP, strong Loyalty reward, rare badge',
    explanationPolicy: 'explain mastery and progression fit',
  },
];

export const SCORING_FACTORS = {
  formula: 'missionScore = segmentFit + activityFit + serviceGapFit + campaignFit + urgencyFit + rewardAffinityFit - frictionPenalty',
  factors: [
    {
      name: 'segmentFit',
      purpose: 'Does the mission match the user scenario from the profile PDF?',
      examples: ['New User -> onboarding', 'EV Owner -> EV charging', 'Safety Focused -> roadside or insurance'],
    },
    {
      name: 'activityFit',
      purpose: 'Does observed activity show the user can realistically do this mission?',
      examples: ['walletTopups > 0 boosts wallet loop', 'roadsideViews > 0 boosts roadside conversion'],
    },
    {
      name: 'serviceGapFit',
      purpose: 'Does the mission close an adoption gap?',
      examples: ['parkingUsage low boosts parking mission', 'roadside off boosts safety mission'],
    },
    {
      name: 'campaignFit',
      purpose: 'Does an active campaign make the mission timely right now?',
      examples: ['EV Week active boosts EV mission', 'Road Safety Month boosts safety mission'],
    },
    {
      name: 'urgencyFit',
      purpose: 'Does the user have a time-sensitive reason to act?',
      examples: ['insurance expiring soon', 'inactive for 28 days'],
    },
    {
      name: 'rewardAffinityFit',
      purpose: 'Does this user historically respond to this kind of reward or flow?',
      examples: ['rewardRedemptions > 0', 'voucher interest', 'high loyalty progression interest'],
    },
    {
      name: 'frictionPenalty',
      purpose: 'Penalize missions that are too hard for the current state.',
      examples: ['don’t show advanced progression to new users', 'don’t show multi-step missions first to inactive users'],
    },
  ],
};

export const ACTIVITY_SIGNAL_RULES = [
  {
    signal: 'walletTopups > 0',
    meaning: 'User is already comfortable with VETC wallet',
    missionEffects: ['boost daily loop', 'boost cashback or wallet missions'],
  },
  {
    signal: 'parkingPayments = 0 and parkingUsage low',
    meaning: 'Parking is a cross-sell opportunity',
    missionEffects: ['boost service discovery', 'boost commuter parking mission'],
  },
  {
    signal: 'insuranceViews > 0 and insurance not enabled or expiring',
    meaning: 'There is intent without conversion',
    missionEffects: ['boost insurance mission', 'boost safety mission'],
  },
  {
    signal: 'roadsideViews > 0 and roadsideEnabled = false',
    meaning: 'User has considered protection but not activated',
    missionEffects: ['boost roadside mission'],
  },
  {
    signal: 'evCharges > 0',
    meaning: 'EV ecosystem usage already exists',
    missionEffects: ['boost EV mission', 'boost charger discovery'],
  },
  {
    signal: 'referralShares > 0',
    meaning: 'User already shows referral intent',
    missionEffects: ['boost referral sprint', 'boost social missions'],
  },
  {
    signal: 'rewardRedemptions > 0',
    meaning: 'User responds to rewards, not only utility',
    missionEffects: ['boost reward-linked missions', 'boost redemption-based loops'],
  },
];
